# Generated by Django 3.2.25 on 2026-01-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex_importer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='created_rows',
            field=models.IntegerField(default=0, verbose_name='Filas Creadas'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='updated_rows',
            field=models.IntegerField(default=0, verbose_name='Filas Actualizadas'),
        ),
    ]
